version: "3.9"
services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  dozzle:
    environment: 
      #username, password and key environment variables adds basic auth to dozzle ui
      #overriden by environment variables
      - DOZZLE_USERNAME=${DOZZLE_USERNAME:-user}
      - DOZZLE_PASSWORD=${DOZZLE_PASSWORD:-password}
      - DOZZLE_KEY=${DOZZLE_KEY:-key}
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #local setup
    #dozzle container runs on port 8080
    #dozzle container exposing port 88
    #dozzle container overrides DOZZLE_PORT and DOZZLE_PORT_CONTAINER when deployed      
    ports:
      - ${DOZZLE_PORT:-88}:${DOZZLE_PORT_CONTAINER:-8080}
  cm-car-info-svc-web: 
    restart: always
    image: "geekymon2/cm-car-info-svc"
    environment: 
      ARTIFACT_NAME: "car-info-service"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
      ENVIRONMENT: "${ENVIRONMENT}"
    #local setup
    #container runs on port 8080
    #container exposing port 8880
    #container overrides APP_PORT and APP_PORT_CONTAINER when deployed
    ports:
      - "${APP_PORT:-8880}:${APP_PORT_CONTAINER:-8080}"
    depends_on: 
      - cm-car-info-svc-db
  cm-car-info-svc-db:
    hostname: "db"
    restart: always
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-P@ssw0rd}"
      MYSQL_DATABASE: "${DB_NAME:-carinfodbdev}"
      MYSQL_USER: sa
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD:-P@ssw0rd}
  cm-discovery-server: 
    hostname: "discovery-sever"
    restart: always
    image: "geekymon2/cm-discovery-server"
    environment: 
      ARTIFACT_NAME: "discovery-server"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
      ENVIRONMENT: "${ENVIRONMENT}"
    #local setup
    #container runs on port 8080
    #container exposing port 8880
    #container overrides APP_PORT and APP_PORT_CONTAINER when deployed
    ports:
      - "${APP_PORT:-8761}:${APP_PORT_CONTAINER:-8761}"
  cm-config-server: 
    hostname: "config-server"
    restart: always
    image: "geekymon2/cm-config-server"
    environment: 
      ARTIFACT_NAME: "config-server"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
      ENVIRONMENT: "${ENVIRONMENT}"
    #local setup
    #container runs on port 8888
    #container exposing port 8888
    #container overrides APP_PORT and APP_PORT_CONTAINER when deployed
    ports:
      - "${APP_PORT:-8888}:${APP_PORT_CONTAINER:-8888}"
volumes:
  db_data: {}
  portainer_data: {}